### ISSUE TITLE
SSR?

### ISSUE THREAD

**Issue by Atinux** [EvodiaAut/vue-cookieconsent-component#1]
Hey @EvodiaAut 

Great idea! Do you think you could make it SSR compatible?

I believe the only thing would be to use `beforeMount` instead of `created` hook (so it could run only on client-side): https://github.com/EvodiaAut/vue-cookieconsent-component/blob/master/src/components/CookieConsent.vue#L106

More details: https://ssr.vuejs.org/en/universal.html

**Comment by EvodiaAut** [comment]
Hi @Atinux,

yes we do that! 👍 
Thank you the next update is in coming soon
