### ISSUE TITLE
Add rel=noopener to link

### ISSUE THREAD

**Issue by manniL** [EvodiaAut/vue-cookieconsent-component#2]
It is best practice to set `rel="noopener"` to external links. See [here](https://mathiasbynens.github.io/rel-noopener/) for more information why/what happens if not.

**Comment by EvodiaAut** [comment]
Hi @manniL,

true story!
Thank you the next update is in coming soon

**Comment by manniL** [comment]
Nice :relaxed: Looking forward to it!

The component plays nicely with [vue-if-bot](https://github.com/Developmint/vue-if-bot) as well. Might be worth adding to the docs :thinking:
